/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter.App;
import converter.lib.Converter;
import converter.lib.Unit;
import converter.exceptions.InvalidFieldException;
import converter.exceptions.NoSelectionException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
/**
 *
 * @author kamalkarwal
 */
public class ConverterGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConverterGUI
     */
    public ConverterGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        signLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        fieldsPanel = new javax.swing.JPanel();
        currentUnit_cb = new javax.swing.JComboBox<>();
        userValue_text = new javax.swing.JTextField();
        result_text = new javax.swing.JTextField();
        convertToUnit_cb = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        temp_rtbn = new javax.swing.JRadioButton();
        speed_rbtn = new javax.swing.JRadioButton();
        area_rbtn = new javax.swing.JRadioButton();
        mass_rbtn = new javax.swing.JRadioButton();
        length_rbtn = new javax.swing.JRadioButton();
        convertPanel = new javax.swing.JPanel();
        convert_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        homePanel.setBackground(new java.awt.Color(153, 153, 153));

        signLabel.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        signLabel.setText("Kamal");

        headingLabel.setBackground(new java.awt.Color(153, 153, 153));
        headingLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Units Convertor");

        fieldsPanel.setBackground(homePanel.getBackground());
        fieldsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Step Two:"));

        currentUnit_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentUnit_cbActionPerformed(evt);
            }
        });

        userValue_text.setFont(new java.awt.Font("Courier", 0, 30)); // NOI18N
        userValue_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        userValue_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userValue_textActionPerformed(evt);
            }
        });
        userValue_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userValue_textKeyTyped(evt);
            }
        });

        result_text.setEditable(false);
        result_text.setFont(new java.awt.Font("Courier", 0, 30)); // NOI18N
        result_text.setForeground(new java.awt.Color(0, 153, 102));
        result_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        result_text.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        result_text.setFocusTraversalKeysEnabled(false);

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(userValue_text, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentUnit_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(result_text, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(convertToUnit_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(118, 118, 118))
        );

        fieldsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {result_text, userValue_text});

        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userValue_text, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(currentUnit_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result_text, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertToUnit_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        fieldsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {result_text, userValue_text});

        buttonPanel.setBackground(fieldsPanel.getBackground());
        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Step One"));

        temp_rtbn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        temp_rtbn.setText("Temperature");
        temp_rtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp_rtbnActionPerformed(evt);
            }
        });

        speed_rbtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        speed_rbtn.setText("Speed");
        speed_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speed_rbtnActionPerformed(evt);
            }
        });

        area_rbtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        area_rbtn.setText("Area");
        area_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_rbtnActionPerformed(evt);
            }
        });

        mass_rbtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        mass_rbtn.setText("Mass");
        mass_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mass_rbtnActionPerformed(evt);
            }
        });

        length_rbtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        length_rbtn.setText("Length");
        length_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                length_rbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(temp_rtbn)
            .addComponent(length_rbtn)
            .addComponent(mass_rbtn)
            .addComponent(area_rbtn)
            .addComponent(speed_rbtn)
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {area_rbtn, length_rbtn, mass_rbtn, speed_rbtn, temp_rtbn});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(length_rbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mass_rbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(area_rbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(speed_rbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temp_rtbn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        convertPanel.setBackground(homePanel.getBackground());
        convertPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step Three", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP));

        convert_btn.setText("Convert");
        convert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout convertPanelLayout = new javax.swing.GroupLayout(convertPanel);
        convertPanel.setLayout(convertPanelLayout);
        convertPanelLayout.setHorizontalGroup(
            convertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convert_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        convertPanelLayout.setVerticalGroup(
            convertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convert_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(convertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(headingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(signLabel)))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(convertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(signLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void speed_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speed_rbtnActionPerformed
        type = Converter.SPEED;
        setViewForButton(speed_rbtn, Unit.SPEED_UNITS);
        
    }//GEN-LAST:event_speed_rbtnActionPerformed

    private void length_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_length_rbtnActionPerformed
        type = Converter.LENGTH;  
        setViewForButton(length_rbtn, Unit.LENGTH_UNITS );
    }//GEN-LAST:event_length_rbtnActionPerformed

    private void mass_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mass_rbtnActionPerformed
        type = Converter.MASS;
        setViewForButton(mass_rbtn, Unit.MASS_UNITS);
    }//GEN-LAST:event_mass_rbtnActionPerformed

    private void area_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_rbtnActionPerformed
        type = Converter.AREA;
        setViewForButton(area_rbtn, Unit.AREA_UNITS);
    }//GEN-LAST:event_area_rbtnActionPerformed

    private void temp_rtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp_rtbnActionPerformed
        type = Converter.TEMP;
        setViewForButton(temp_rtbn, Unit.TEMP_UNITS);
    }//GEN-LAST:event_temp_rtbnActionPerformed

    
    private void userValue_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userValue_textKeyTyped
        // TODO add your handling code here:
        
        boolean validKey = false;
        int key =(int) evt.getKeyChar();
        if( key>=48 && key <=57) {
            validKey = true;
        } else if ( key == 8 || key == 46) {
            validKey = true;
        }
        
        if(!validKey) {
            JOptionPane.showMessageDialog(rootPane,"Please Correct the last Entry","Invalid Character",
                                JOptionPane.WARNING_MESSAGE);
        }
        
       
    }//GEN-LAST:event_userValue_textKeyTyped

    private void currentUnit_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentUnit_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentUnit_cbActionPerformed

    private void convert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_btnActionPerformed
        String result = "";
        currentUnit = (String) currentUnit_cb.getSelectedItem();
        newUnit = (String) convertToUnit_cb.getSelectedItem();
        quantity = userValue_text.getText();
        try {
        result = Converter.convert(type, quantity, currentUnit, newUnit);
        } catch (InvalidFieldException nex) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter a Number","Number Error!",JOptionPane.ERROR_MESSAGE);
        } catch (NoSelectionException inex) {
            JOptionPane.showMessageDialog(rootPane, "Please select the type of Conversion","Selection Error!",JOptionPane.ERROR_MESSAGE);
        }
        result_text.setText(result);
    }//GEN-LAST:event_convert_btnActionPerformed

    private void userValue_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userValue_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userValue_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterGUI().setVisible(true);
            }
        });
    }
    /**
     * This method should be used to set the view of the combo boxes according to
     * the button. Also passes the information to the last button variable.
     * @param button Current radio button
     * @param units  type of radio button selected
     */
    private void setViewForButton(JRadioButton button, String [] units ) {
        clearLastButton();
        setupFieldPanel(units);
        lastButton = button; // set this button as last selected
          
    }
    /**
     * Takes String array  as an input and setup the combo boxes in fieldsPanel (JPanel)
     * @param units String [] type of units as selected by radio button 
     */
    private void setupFieldPanel(String[] currentUnits) {
        currentUnit_cb.removeAllItems();
        convertToUnit_cb.removeAllItems();
        
        for (String unit : currentUnits ) {
            
            currentUnit_cb.addItem(unit);
            
            convertToUnit_cb.addItem(unit);
            
        }
      
    }
    /**
     * This method should be called by every radio button action to clear the last
     * selected button. To make sure there is only one button selected at one time.
     * 
     */
    private void clearLastButton () {
         //if last button is not null clear the selection of lastbutton
        if(lastButton != null )
            lastButton.setSelected(false);
        
    }
   
   
    
    private String type;
    private String currentUnit;
    private String newUnit;
    private String quantity;
    
    private javax.swing.JRadioButton lastButton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton area_rbtn;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel convertPanel;
    private javax.swing.JComboBox<String> convertToUnit_cb;
    private javax.swing.JButton convert_btn;
    private javax.swing.JComboBox<String> currentUnit_cb;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JRadioButton length_rbtn;
    private javax.swing.JRadioButton mass_rbtn;
    private javax.swing.JTextField result_text;
    private javax.swing.JLabel signLabel;
    private javax.swing.JRadioButton speed_rbtn;
    private javax.swing.JRadioButton temp_rtbn;
    private javax.swing.JTextField userValue_text;
    // End of variables declaration//GEN-END:variables
}
